- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: course name
    private: false 
  - name: TRAINER
    prompt: Trainer name
    private: false
  - name: DURATION
    prompt: Duration
    private: false
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"      