- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: course name
    # private: false (if you want to show the data enterning in the server)
  - name: TRAINER
    prompt: Trainer name
    # private: false  (if you want to show the data enterning in the server) 
  - name: DURATION
    prompt: Duration
    #private: false (if you want to show the data enterning in the server)
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"      