- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: course name
  - name: TRAINER
    prompt: Trainer name
  - name: DURATION
    prompt: Duration
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"      