- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: print the course name
  - name: TRAINER
    prompt: print the trainer name
  - name: DURATION
    prompt: enter the duration
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"      