- name:
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop: #here we use loop because all packages should run in one single stage
    - { name: 'mysql', state: 'absent' }  
    - { name: 'nginx', state: 'present' } 
    - { name: 'postfix', state: 'present' } 
    - { name: 'httpd', state: 'present' } 